# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Code generated by the Google Gen AI SDK generator DO NOT EDIT.

import logging
import typing
from typing import Optional, Union
from google.genai import _common
from pydantic import Field
from typing_extensions import TypedDict

logger = logging.getLogger('google_genai.types')

T = typing.TypeVar('T', bound='GenerateContentResponse')


class LLMMetric(_common.CaseInSensitiveEnum):
  """LLM-based metrics."""

  TEXT_QUALITY = 'TEXT_QUALITY'
  INSTRUCTION_FOLLOWING = 'INSTRUCTION_FOLLOWING'


class _LoadLLMMetricParameters(_common.BaseModel):
  """Parameters for loading a LLM metric."""

  metric_name: Optional[str] = Field(
      default=None, description="""Name of the LLM metric."""
  )
  version: Optional[str] = Field(
      default=None, description="""Version of the LLM metric."""
  )
  uri: Optional[str] = Field(
      default=None, description="""GCS URI of the LLM metric."""
  )


class _LoadLLMMetricParametersDict(TypedDict, total=False):
  """Parameters for loading a LLM metric."""

  metric_name: Optional[str]
  """Name of the LLM metric."""

  version: Optional[str]
  """Version of the LLM metric."""

  uri: Optional[str]
  """GCS URI of the LLM metric."""


_LoadLLMMetricParametersOrDict = Union[
    _LoadLLMMetricParameters, _LoadLLMMetricParametersDict
]


class CustomLLMMetric(_common.BaseModel):
  """Class for custom LLM-based metrics."""

  metric_name: Optional[str] = Field(
      default=None,
      description="""Name of the custom LLM-based metric.
      """,
  )
  version: Optional[str] = Field(
      default=None,
      description="""Version of the custom LLM-based metric.
      """,
  )


class CustomLLMMetricDict(TypedDict, total=False):
  """Class for custom LLM-based metrics."""

  metric_name: Optional[str]
  """Name of the custom LLM-based metric.
      """

  version: Optional[str]
  """Version of the custom LLM-based metric.
      """


CustomLLMMetricOrDict = Union[CustomLLMMetric, CustomLLMMetricDict]


class _EvaluateLLMMetricParameters(_common.BaseModel):
  """Parameters for loading a LLM metric."""

  dataset: Optional[str] = Field(
      default=None, description="""Name of the LLM metric."""
  )
  metrics: Optional[LLMMetric] = Field(
      default=None, description="""List of LLM metrics to evaluate."""
  )


class _EvaluateLLMMetricParametersDict(TypedDict, total=False):
  """Parameters for loading a LLM metric."""

  dataset: Optional[str]
  """Name of the LLM metric."""

  metrics: Optional[LLMMetric]
  """List of LLM metrics to evaluate."""


_EvaluateLLMMetricParametersOrDict = Union[
    _EvaluateLLMMetricParameters, _EvaluateLLMMetricParametersDict
]


class EvalResult(_common.BaseModel):
  """Result of evaluating an LLM metric."""

  dashboard_uri: Optional[str] = Field(
      default=None,
      description="""URI to view the evaluation results in the Cloud console.""",
  )


class EvalResultDict(TypedDict, total=False):
  """Result of evaluating an LLM metric."""

  dashboard_uri: Optional[str]
  """URI to view the evaluation results in the Cloud console."""


EvalResultOrDict = Union[EvalResult, EvalResultDict]
